version: "3.8"

services:
  frontend:
    container_name: frontend
    # volumes:
    #   - ./frontend:/app
    build: ./frontend
    ports:
      - 8080:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
