version: "3.8"

services:
  web:
    # build: ./frontend
    image: node:18-alpine
    container_name: web
    expose:
      - 8080
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/app
    command: sh -c "cd /app && npm install && npm start"
      # - /app/node_modules
    networks:
      - app_network

  api:
    # build: ./backend
    image: node:18-alpine
    container_name: api
    expose:
      - 8081
    ports:
      - 8081:3000
    volumes:
      - ./backend:/app
    command: sh -c "cd /app && npm install && npm run dev"
      # - /app/node_modules
    networks:
      - app_network

  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 8082:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p123456
      POSTGRES_DB: default_database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
